In [1]:
import numpy
import pandas
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

Using TensorFlow backend.


In [2]:
import sklearn

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
from sklearn.metrics import mean_squared_error

In [5]:
# for reproducability of the results let's fix the seed function
numpy.random.seed(1234)

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
#dataset = pandas.read_csv('C:/Users/Dell/Downloads/international-airline-passengers.csv',usecols=[1],engine='python',skipfooter=3)
dataset= pd.read_csv('international-airline-passengers.csv',usecols=[1],engine='python',skipfooter=3)


In [7]:
dataset.head()

International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60
0                                                112                             
1                                                118                             
2                                                132                             
3                                                129                             
4                                                121

In [8]:
dataset = dataset.values
dataset = dataset.astype('float32')

In [9]:
# normaliza the dataset
scaler = MinMaxScaler(feature_range=(0,1))
dataset = scaler.fit_transform(dataset)

In [10]:
dataset

array([[0.01544401],
       [0.02702703],
       [0.05405405],
       [0.04826255],
       [0.03281853],
       [0.05984557],
       [0.08494207],
       [0.08494207],
       [0.06177607],
       [0.02895753],
       [0.        ],
       [0.02702703],
       [0.02123553],
       [0.04247104],
       [0.07142857],
       [0.05984557],
       [0.04054055],
       [0.08687258],
       [0.12741312],
       [0.12741312],
       [0.10424709],
       [0.05598456],
       [0.01930502],
       [0.06949806],
       [0.07915059],
       [0.08880308],
       [0.14285713],
       [0.11389962],
       [0.13127413],
       [0.14285713],
       [0.18339768],
       [0.18339768],
       [0.15444016],
       [0.11196911],
       [0.08108109],
       [0.1196911 ],
       [0.12934363],
       [0.14671814],
       [0.17181468],
       [0.14864865],
       [0.15250966],
       [0.22007722],
       [0.24324325],
       [0.26640925],
       [0.2027027 ],
       [0.16795367],
       [0.13127413],
       [0.173

In [11]:
# split the dataset into train and test 
train_size = int(len(dataset)*0.67)

In [12]:
print(train_size)

96


In [13]:
test_size = len(dataset) - train_size

In [14]:
print(test_size)

48


In [15]:
train,test = dataset[0:train_size,:],dataset[train_size:len(dataset),:]

In [16]:
print(len(train), len(test))

96 48


In [17]:
# create dataset matrix
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back),0]
        dataX.append(a)
        dataY.append(dataset[i+look_back,0])
    return numpy.array(dataX),numpy.array(dataY)

In [18]:
#reshape the dataset X =current time, and Yt+1 =future time period
look_back =1
trainX, trainY = create_dataset(train,look_back)
testX, testY = create_dataset(test,look_back)

In [19]:
trainX = numpy.reshape(trainX,(trainX.shape[0],1,trainX.shape[1]))
testX = numpy.reshape(testX,(testX.shape[0],1,testX.shape[1]))

In [20]:
print(testX)

[[[0.4073359 ]]

 [[0.3803089 ]]

 [[0.48648646]]

 [[0.47104248]]

 [[0.484556  ]]

 [[0.6138996 ]]

 [[0.6969112 ]]

 [[0.70077217]]

 [[0.57915056]]

 [[0.46911195]]

 [[0.38803086]]

 [[0.44787642]]

 [[0.45559844]]

 [[0.4131274 ]]

 [[0.4980695 ]]

 [[0.47104248]]

 [[0.49999997]]

 [[0.6389961 ]]

 [[0.7471043 ]]

 [[0.7741313 ]]

 [[0.57915056]]

 [[0.492278  ]]

 [[0.3976834 ]]

 [[0.44980696]]

 [[0.49420848]]

 [[0.45945945]]

 [[0.5830116 ]]

 [[0.5637065 ]]

 [[0.61003864]]

 [[0.71042466]]

 [[0.8571429 ]]

 [[0.8783784 ]]

 [[0.69305015]]

 [[0.5849421 ]]

 [[0.4980695 ]]

 [[0.58108103]]

 [[0.6042471 ]]

 [[0.554054  ]]

 [[0.60810804]]

 [[0.6891892 ]]

 [[0.71042466]]

 [[0.8320464 ]]

 [[1.        ]]

 [[0.96911204]]

 [[0.7799227 ]]

 [[0.6891892 ]]]


In [21]:
# let's create  a RNN or LSTM model
model = Sequential()
model.add(LSTM(4,input_shape=(1,look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error',optimizer='adam')

# fit the model
model.fit(trainX,trainY,batch_size=1,verbose=2)

Epoch 1/1
 - 2s - loss: 0.0330


In [22]:
# make predictions
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

In [23]:
print(trainPredict)

[[0.10216756]
 [0.10405409]
 [0.10845263]
 [0.10751058]
 [0.10499708]
 [0.10939435]
 [0.11347069]
 [0.11347069]
 [0.10970818]
 [0.10436845]
 [0.09965138]
 [0.10405409]
 [0.10311091]
 [0.10656823]
 [0.1112767 ]
 [0.10939435]
 [0.10625407]
 [0.11378391]
 [0.12034757]
 [0.12034757]
 [0.11660038]
 [0.10876657]
 [0.10279648]
 [0.11096308]
 [0.11253071]
 [0.11409708]
 [0.12283977]
 [0.11816292]
 [0.12097108]
 [0.12283977]
 [0.12935501]
 [0.12935501]
 [0.12470543]
 [0.11785054]
 [0.11284408]
 [0.11909962]
 [0.12065937]
 [0.123462  ]
 [0.12749782]
 [0.12377299]
 [0.12439471]
 [0.13521035]
 [0.13888603]
 [0.14254245]
 [0.13244188]
 [0.12687796]
 [0.12097108]
 [0.1278076 ]
 [0.12842688]
 [0.12842688]
 [0.14071676]
 [0.14041199]
 [0.13858047]
 [0.14284623]
 [0.14919057]
 [0.15158887]
 [0.1410214 ]
 [0.13305792]
 [0.123462  ]
 [0.12997326]
 [0.13089982]
 [0.12594743]
 [0.14041199]
 [0.13796887]
 [0.14010707]
 [0.14919057]
 [0.1604814 ]
 [0.15783113]
 [0.1476863 ]
 [0.13858047]
 [0.13059106]
 [0.13

In [24]:
print(testPredict)

[[0.16428146]
 [0.16018769]
 [0.17603153]
 [0.17376828]
 [0.17574944]
 [0.19410309]
 [0.20525071]
 [0.20575637]
 [0.18928543]
 [0.1734843 ]
 [0.16136132]
 [0.17034604]
 [0.17149037]
 [0.16515353]
 [0.17771918]
 [0.17376828]
 [0.1779996 ]
 [0.19752797]
 [0.21173275]
 [0.21513948]
 [0.18928543]
 [0.17687643]
 [0.16282393]
 [0.17063245]
 [0.17715755]
 [0.1720612 ]
 [0.18982497]
 [0.18711673]
 [0.1935721 ]
 [0.20701542]
 [0.22522703]
 [0.22771472]
 [0.20474389]
 [0.19009435]
 [0.17771918]
 [0.18955532]
 [0.19277355]
 [0.18575293]
 [0.19330615]
 [0.20423588]
 [0.20701542]
 [0.22223791]
 [0.24121699]
 [0.23790908]
 [0.21586177]
 [0.20423588]]


In [25]:
# reverse the predicted values to thee actual time series values using inverse tranform function
trainPredict = scaler.inverse_transform(trainPredict) 
testPredict = scaler.inverse_transform(testPredict)

trainY = scaler.inverse_transform([trainY])
testY = scaler.inverse_transform([testY])

In [26]:
print(trainPredict, trainY)

[[156.9228 ]
 [157.90002]
 [160.17847]
 [159.69049]
 [158.38849]
 [160.66628]
 [162.77783]
 [162.77783]
 [160.82883]
 [158.06285]
 [155.61942]
 [157.90002]
 [157.41145]
 [159.20235]
 [161.64134]
 [160.66628]
 [159.03961]
 [162.94008]
 [166.34006]
 [166.34006]
 [164.39899]
 [160.3411 ]
 [157.24857]
 [161.47887]
 [162.29091]
 [163.1023 ]
 [167.63101]
 [165.20839]
 [166.66302]
 [167.63101]
 [171.0059 ]
 [171.0059 ]
 [168.59741]
 [165.04659]
 [162.45323]
 [165.6936 ]
 [166.50156]
 [167.95331]
 [170.04387]
 [168.11443]
 [168.43646]
 [174.03897]
 [175.94296]
 [177.83699]
 [172.60489]
 [169.72278]
 [166.66302]
 [170.20433]
 [170.52513]
 [170.52513]
 [176.89128]
 [176.73341]
 [175.78468]
 [177.99434]
 [181.28072]
 [182.52304]
 [177.04909]
 [172.92401]
 [167.95331]
 [171.32616]
 [171.8061 ]
 [169.24078]
 [176.73341]
 [175.46788]
 [176.57545]
 [181.28072]
 [187.12936]
 [185.75653]
 [180.50151]
 [175.78468]
 [171.64618]
 [175.78468]
 [177.83699]
 [176.41743]
 [181.74722]
 [182.05782]
 [182.21298]

In [27]:
print(testPredict, testY)

[[189.0978 ]
 [186.97722]
 [195.18433]
 [194.01198]
 [195.03822]
 [204.54541]
 [210.31987]
 [210.5818 ]
 [202.04985]
 [193.86487]
 [187.58516]
 [192.23926]
 [192.83202]
 [189.54953]
 [196.05853]
 [194.01198]
 [196.20378]
 [206.31949]
 [213.67757]
 [215.44225]
 [202.04985]
 [195.622  ]
 [188.3428 ]
 [192.3876 ]
 [195.76761]
 [193.1277 ]
 [202.32933]
 [200.92645]
 [204.27036]
 [211.234  ]
 [220.6676 ]
 [221.95622]
 [210.05734]
 [202.46887]
 [196.05853]
 [202.18965]
 [203.8567 ]
 [200.22002]
 [204.13258]
 [209.79419]
 [211.234  ]
 [219.11925]
 [228.95041]
 [227.23691]
 [215.81639]
 [209.79419]] [[301.00001152 355.999993   348.00001085 355.00000681 421.9999924
  465.0000161  466.99998848 403.99999397 346.99999379 304.99998716
  335.99999132 339.99999783 317.99999288 362.00000277 348.00001085
  362.99998896 434.99999813 491.00002756 505.00001948 403.99999397
  359.00001333 310.00001073 337.00000838 359.99999952 342.00000109
  406.0000281  395.99998094 420.00002002 471.99998119 548.00004318


In [28]:
# calculate the RMSE root mean square error
trainScore = math.sqrt(mean_squared_error(trainY[0],trainPredict[:,0]))
print ('Train Score: %.2f RMSE' % (trainScore))

Train Score: 72.92 RMSE


In [29]:
testScore = math.sqrt(mean_squared_error(testY[0],testPredict[:,0]))
print ('Test Score: %.2f RMSE' % (testScore))

Test Score: 223.41 RMSE
